### PR TITLE
Use prop-types

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/Hyperline/hyperline/issues/129

### CODE REVIEW

**Comment by jstnbchnn** [comment]
Can this get merged?

**Comment by dougmaitelli** [comment]
The changes are simple and don't seem to cause any problem, can this be merged please? Would like to be able to use the plugin on Hyper 2.1.1

**Comment by jstnbchnn** [comment]
I'm gonna get aggressive here. 
Pinging: 
@nicktikhonov 
@timneutkens 
@stefanivic 
@henrikdahl

**Comment by NickTikhonov** [comment]
Hey all - apologies for the delay!

**Pull request merged**
