### PR TITLE
Added 'type' option to get the remote or local ip

### PR DESCRIPTION
**Pull request by edoren**
I added a type option to the ip.js plugin to get the remote or local ip

### CODE REVIEW

**Comment by timneutkens** [comment]
This is awesome. I'm going to ask you to make this pull request again against the develop branch. We're going to be actively working towards a 2.0 release.

**Comment by timneutkens** [comment]
Just merged develop with master. So you can base it off the current master.

**Comment by edoren** [comment]
Sure, I'm gonna check the changes and make the pull request again

**Comment by timneutkens** [comment]
Thank you very much ❤️

**Comment by edoren** [comment]
@timneutkens is there gonna be a way to configure the active plugins?

**Comment by timneutkens** [comment]
We're going to move all plugins into separate packages.

**Pull request closed without merging**
